sudo: false
language: node_js
node_js:
  - '6'
  - '7'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
env:
  global:
    # ALI_SDK_OSS_ID
    - secure: "HVsim0t5hMxjkQc52cT24eAihoziVyOckZ6XMjJZHb/AKfNNHge4UbPZUkiBMsP1TBBlGLXI1/llA1vhPUApnW8HN6mAhnMvqKIbCT6gdyKJx/LkRRxnwifKYIBLnduCvq4j+yJKBOt/A9kVNCxw7z3gW/CXmW73L1wmGkM1WQkxvqjd+I4BQ03vWrLBk7ue7wQ8D0MmzgcGQku9JtWnNNntTYt+SLjMoaa77hg7iq28aQ195Hv0EEHo+0XuxnYJWQYAc49fc9xZ5optzHnrtOQqE2fusmmkDJb5bxrx+5qtBPl56O8dpOcPwEec0En5TI1vz2duROQCb77ON7bw0YMZZJTrR/BsWtnGehgZd0HYqT5RCyvXW/tSt0dk3XOKCpfsUtP9qzjrXjUGCc9JDZE6gf9rP1Jw59Qqcfq5/oh+aJpw7rVmNjPd4vDhQk8yQknLK3F8jV4Xhqmkll7S4xJx6D9lAf9pvFiQjWEMZ3hbMFyiRNr2FapUNUOJTwHjadASjZJqR7FHr7WM2nr2+GsgHivbsrnUqlU4oyDQi4TDPftfVjIWBLPy4PLlgGa83S6zbUINxYsXZRCp64K/VplZT/PFGa+2X/3i/QkUX27oH+5Yt38aN1BEe80xUXuY6QXxvdwnAFijPA5iVGGdCzk8T8j2KiN6rhLO089Our4="
    # ALI_SDK_OSS_SECRET
    - secure: "HNfJV2WTFMGH9pKwM9zWxHUKAbK1LzLrWwam/v7ZVouZVVSd6cWytlT82FGWRl5+zCefRPN8dPcunGZokj7Z1n2dWVg9C2PX7cGvRz24FB17wHDtAsR01v29JLSnLGIIr/snjLM9nWT91HedEF1HufnnO6AaoAGlf0cm2fpZNczzr9xpnrh6W7rhaC49GMPhjT8bFig4OXgkGJIU8GvbCJgjwCru5UCYSCwBhjvPqdwcEKY8bC8F1aECa9EMsf0/OLIqzDWGRVRtFLAXlczE+U8cFAuJxxsI3iKbG9R6r43r9tp9SBOFdAHwKGbBa4rqqbQ2IspFkLOgQwVLC6xYZvl3qgRB9dDwW6h/sIG5rtyNJ7zfaNVNSMvQU/CLg4zMVNIU0HIp7Bqc9+4CO20Gv+ZmxH3jPpac6Q9nRv0oXWnoLSfozbssXenHnhdFxkLytZ1bwxAM9XhK1ZzWN7XZ5z5yEKTnKxRp5ec+pioaJAxuQPVfI149YFjJB6Uljrx0UvD5/38cxr/Nu8rLvHtOVL8sy+F37yOrpfa8qJO+U7++VP8qZaDtMca4HfTJCifhe6jekfLIOn/CnlV77HY52jZdn+BUJ46Rm0OkTYW7yyE5nSTo75E/FEbsefd50bsgEx5vDp82XH2wjgJ5dk6RlcRUGxr9HkIRjL8WyDdkoR4="
    # ALI_SDK_OSS_REGION
    - secure: "fOe9Zh0qluRMVjnx5Xa5zW9xDfAx7alklRbiLKF5jWx7sPszQ8ssWcdq7BWH4JJD3HybUN06uipB6YT43tRhcpajd3W04hcs6lEiTwZ90SjKC35rXhuoJoZBUxt83pTbAzbv2aH3IeE+O6r35MQ6GTLqWXpDeublScZTR3he/c/YN7XucPW3ABJtdabSBai4RwZNj9NZyR4hJJ/i+u5q5u/tqNaq6Vbwihc85Of5SyrKx0RIh8o/HwrFatmMPqGRf8bYYRl2w4MKKB+Zq4SYR+58KpgB4VvhnPhR6ellJnb+uNhdQyQ/9QTbAQ58JAXNZZqNXoBcstcbFT+NohQj4a0P+Fb7IqnEESTFWZuy2smcr+0KLaHeWoTnl09I0Ipkzch44uXPrJV/jSvQtTtC2TOhY+sdRYzWOxJ4nLQt3cBui1VpqjBlCQvapb0GXuGZE7qY0ityBHCiB//6MwXq82eGVzJrnrti9/h518qNG/c6KEWdNITVHTtCds1byz7iex9v57PncFj0jbWiDHgS3W9r1k7f3HnB44BXLKKGm3HV3dVkdorXpFIMax8VZgocQcg6ueBzEgvIliiUA2yt1SjqyDu4AD0yJzDKEYtnkiZsXXXUHOROA9JR1SUD20KEH+J6Z32oE4D5FaCDaJ1j9YnzrC+zQYl48iWmeZ2VTE4="
